name: Build manylinux wheels

on: [pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    container:
        image: "quay.io/pypa/manylinux2014_x86_64"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        run: |
            pyver=`echo '${{ matrix.python-version }}' | tr -d '.'`
            pypath=`echo /opt/python/cp${pyver}-cp${pyver}*/bin`
            export PATH=$pypath:$PATH
            python -m pip install wheel
            python setup.py bdist_wheel --plat-name=manylinux2014_x86_64 --universal

      - uses: actions/upload-artifact@v2
        with:
          name: Upload wheels
          path: dist/

